export const data = [
  {
    id:1,
    title: 'Lorem, ipsum.',
    category: 'breakfast',
    price: 15.75,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2017/08/smoothie-bowl-3a8632c.jpg?quality=90&resize=556,505',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id: 7,
    title: 'Lorem, ipsum.',
    category: 'lunch',
    price: 48.95,
    img: 'https://simply-delicious-food.com/wp-content/uploads/2018/07/mexican-lunch-bowls-3.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id: 11,
    title: 'Lorem, ipsum.',
    category: 'cocktail',
    price: 8.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3EJ9Z-7rFEqgx-nINgEw5S_yGBOClksoxQA&usqp=CAU',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id:2,
    title: 'Lorem, ipsum.',
    category: 'breakfast',
    price: 13.80,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2017/08/smoothie-bowl-3a8632c.jpg?quality=90&resize=556,505',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id:3,
    title: 'Lorem, ipsum.',
    category: 'breakfast',
    price: 20.95,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2017/08/smoothie-bowl-3a8632c.jpg?quality=90&resize=556,505',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id:4,
    title: 'Lorem, ipsum.',
    category: 'breakfast',
    price: 10.50,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2017/08/smoothie-bowl-3a8632c.jpg?quality=90&resize=556,505',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id:5,
    title: 'Lorem, ipsum.',
    category: 'breakfast',
    price: 25.50,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2017/08/smoothie-bowl-3a8632c.jpg?quality=90&resize=556,505',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id: 6,
    title: 'Lorem, ipsum.',
    category: 'lunch',
    price: 98.45,
    img: 'https://simply-delicious-food.com/wp-content/uploads/2018/07/mexican-lunch-bowls-3.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id: 8,
    title: 'Lorem, ipsum.',
    category: 'lunch',
    price: 56.00,
    img: 'https://simply-delicious-food.com/wp-content/uploads/2018/07/mexican-lunch-bowls-3.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id: 9,
    title: 'Lorem, ipsum.',
    category: 'cocktail',
    price: 15.75,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3EJ9Z-7rFEqgx-nINgEw5S_yGBOClksoxQA&usqp=CAU',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id: 10,
    title: 'Lorem, ipsum.',
    category: 'cocktail',
    price: 13.75,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3EJ9Z-7rFEqgx-nINgEw5S_yGBOClksoxQA&usqp=CAU',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
  {
    id:12,
    title: 'Lorem, ipsum.',
    category: 'cocktail',
    price: 32.6,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3EJ9Z-7rFEqgx-nINgEw5S_yGBOClksoxQA&usqp=CAU',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia dignissimos enim cum soluta sunt sequi.',
  },
]